// Code generated by "stringer -type=ScoreLine"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ones-0]
	_ = x[Twos-1]
	_ = x[Threes-2]
	_ = x[Fours-3]
	_ = x[Fives-4]
	_ = x[Sixes-5]
	_ = x[ThreeOfAKind-6]
	_ = x[FourOfAKind-7]
	_ = x[SmallStraight-8]
	_ = x[LargeStraight-9]
	_ = x[FullHouse-10]
	_ = x[Yahtzee-11]
	_ = x[Chance-12]
	_ = x[ScoreLineCount-13]
}

const _ScoreLine_name = "OnesTwosThreesFoursFivesSixesThreeOfAKindFourOfAKindSmallStraightLargeStraightFullHouseYahtzeeChanceScoreLineCount"

var _ScoreLine_index = [...]uint8{0, 4, 8, 14, 19, 24, 29, 41, 52, 65, 78, 87, 94, 100, 114}

func (i ScoreLine) String() string {
	if i < 0 || i >= ScoreLine(len(_ScoreLine_index)-1) {
		return "ScoreLine(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScoreLine_name[_ScoreLine_index[i]:_ScoreLine_index[i+1]]
}
